import { ItineraryData } from "./types";

/**
 * Mock itinerary data: 5-day Tokyo + Osaka trip
 */
export const mockItinerary: ItineraryData = {
  id: "itin-001",
  title: "日本东京+大阪 5日游",
  destination: "日本 (东京 / 大阪)",
  startDate: "2026-04-10",
  endDate: "2026-04-14",
  travelers: 2,
  totalBudget: 20000,
  currency: "CNY",
  status: "confirmed",
  days: [
    {
      day: 1,
      date: "2026-04-10",
      title: "抵达东京 & 新宿探索",
      items: [
        {
          time: "08:00",
          title: "上海浦东 -> 东京成田",
          description: "春秋航空 9C8515，飞行约3小时",
          type: "transport",
          duration: "3h",
          location: { lat: 35.7647, lng: 140.3864, label: "成田国际机场" },
        },
        {
          time: "12:00",
          title: "成田机场 -> 新宿",
          description: "乘坐成田特快 N'EX 前往新宿站",
          type: "transport",
          duration: "1.5h",
          location: { lat: 35.6896, lng: 139.7006, label: "新宿站" },
        },
        {
          time: "14:00",
          title: "入住新宿华盛顿酒店",
          description: "标准双床房，步行5分钟到新宿站",
          type: "hotel",
          location: { lat: 35.6878, lng: 139.6977, label: "新宿华盛顿酒店" },
        },
        {
          time: "15:30",
          title: "新宿御苑",
          description: "日本代表性庭院，樱花季节绝佳观赏地",
          type: "attraction",
          duration: "2h",
          location: { lat: 35.6852, lng: 139.7100, label: "新宿御苑" },
        },
        {
          time: "18:00",
          title: "歌舞伎町晚餐",
          description: "一蘭拉面新宿店，体验正宗豚骨拉面",
          type: "food",
          duration: "1h",
          location: { lat: 35.6938, lng: 139.7034, label: "歌舞伎町" },
        },
      ],
    },
    {
      day: 2,
      date: "2026-04-11",
      title: "东京经典一日游",
      items: [
        {
          time: "08:00",
          title: "筑地场外市场早餐",
          description: "新鲜海鲜丼饭和玉子烧",
          type: "food",
          duration: "1h",
          location: { lat: 35.6654, lng: 139.7707, label: "筑地场外市场" },
        },
        {
          time: "09:30",
          title: "浅草寺 & 仲见世通",
          description: "东京最古老的寺庙，雷门打卡必到",
          type: "attraction",
          duration: "2h",
          location: { lat: 35.7148, lng: 139.7967, label: "浅草寺" },
        },
        {
          time: "12:00",
          title: "东京晴空塔",
          description: "634米高塔，远眺东京全景",
          type: "attraction",
          duration: "1.5h",
          location: { lat: 35.7101, lng: 139.8107, label: "东京晴空塔" },
        },
        {
          time: "14:00",
          title: "秋叶原电器街",
          description: "二次元圣地，电子产品和动漫周边",
          type: "activity",
          duration: "2h",
          location: { lat: 35.7023, lng: 139.7745, label: "秋叶原" },
        },
        {
          time: "17:00",
          title: "涩谷十字路口 & 忠犬八公像",
          description: "世界最繁忙路口，体验东京脉搏",
          type: "attraction",
          duration: "1h",
          location: { lat: 35.6580, lng: 139.7016, label: "涩谷十字路口" },
        },
        {
          time: "18:30",
          title: "涩谷烤肉晚餐",
          description: "叙叙苑烤肉，黑毛和牛套餐",
          type: "food",
          duration: "1.5h",
          location: { lat: 35.6595, lng: 139.6983, label: "叙叙苑涩谷店" },
        },
      ],
    },
    {
      day: 3,
      date: "2026-04-12",
      title: "东京 -> 大阪 & 道顿堀",
      items: [
        {
          time: "07:30",
          title: "酒店早餐 & 退房",
          description: "新宿华盛顿酒店自助早餐",
          type: "food",
          duration: "1h",
          location: { lat: 35.6878, lng: 139.6977, label: "新宿华盛顿酒店" },
        },
        {
          time: "09:00",
          title: "东京站 -> 新大阪站",
          description: "新干线 Nozomi 号，东海道新干线",
          type: "transport",
          duration: "2.5h",
          location: { lat: 34.7334, lng: 135.5001, label: "新大阪站" },
        },
        {
          time: "12:00",
          title: "入住大阪难波东方酒店",
          description: "步行3分钟到道顿堀，地理位置绝佳",
          type: "hotel",
          location: { lat: 34.6672, lng: 135.5013, label: "难波东方酒店" },
        },
        {
          time: "13:00",
          title: "道顿堀美食街",
          description: "章鱼小丸子、大阪烧、串炸，一网打尽",
          type: "food",
          duration: "2h",
          location: { lat: 34.6687, lng: 135.5025, label: "道顿堀" },
        },
        {
          time: "15:30",
          title: "心斋桥筋商店街",
          description: "大阪最大的购物区，药妆店集中地",
          type: "activity",
          duration: "2.5h",
          location: { lat: 34.6733, lng: 135.5008, label: "心斋桥" },
        },
        {
          time: "19:00",
          title: "法善寺横丁晚餐",
          description: "怀旧小巷中的地道日式居酒屋",
          type: "food",
          duration: "1.5h",
          location: { lat: 34.6693, lng: 135.5042, label: "法善寺横丁" },
        },
      ],
    },
    {
      day: 4,
      date: "2026-04-13",
      title: "大阪文化之旅",
      items: [
        {
          time: "08:30",
          title: "黑门市场早餐",
          description: "大阪的厨房，新鲜刺身和烤海鲜",
          type: "food",
          duration: "1h",
          location: { lat: 34.6652, lng: 135.5066, label: "黑门市场" },
        },
        {
          time: "10:00",
          title: "大阪城天守阁",
          description: "丰臣秀吉建造的名城，登顶俯瞰大阪",
          type: "attraction",
          duration: "2h",
          location: { lat: 34.6873, lng: 135.5259, label: "大阪城天守阁" },
        },
        {
          time: "13:00",
          title: "通天阁 & 新世界",
          description: "大阪地标塔，品尝炸串名店",
          type: "attraction",
          duration: "2h",
          location: { lat: 34.6522, lng: 135.5064, label: "通天阁" },
        },
        {
          time: "15:30",
          title: "天王寺动物园",
          description: "日本第三古老的动物园，亲子好去处",
          type: "attraction",
          duration: "1.5h",
          location: { lat: 34.6487, lng: 135.5081, label: "天王寺动物园" },
        },
        {
          time: "18:00",
          title: "梅田空中庭园展望台",
          description: "173米高空看大阪夜景，浪漫约会圣地",
          type: "attraction",
          duration: "1.5h",
          location: { lat: 34.7053, lng: 135.4903, label: "梅田空中庭园" },
        },
      ],
    },
    {
      day: 5,
      date: "2026-04-14",
      title: "大阪最后一天 & 返程",
      items: [
        {
          time: "08:00",
          title: "酒店早餐",
          description: "酒店自助早餐后退房",
          type: "food",
          duration: "1h",
          location: { lat: 34.6672, lng: 135.5013, label: "难波东方酒店" },
        },
        {
          time: "09:30",
          title: "日本桥电器街",
          description: "大阪版秋叶原，购买伴手礼",
          type: "activity",
          duration: "1.5h",
          location: { lat: 34.6598, lng: 135.5055, label: "日本桥电器街" },
        },
        {
          time: "11:30",
          title: "难波 -> 关西机场",
          description: "乘坐南海电铁 Rapi:t 特急",
          type: "transport",
          duration: "40min",
          location: { lat: 34.4320, lng: 135.2304, label: "关西国际机场" },
        },
        {
          time: "14:00",
          title: "关西机场免税店购物",
          description: "最后的购物机会，白色恋人、ROYCE巧克力",
          type: "activity",
          duration: "1.5h",
          location: { lat: 34.4320, lng: 135.2304, label: "关西机场免税店" },
        },
        {
          time: "16:30",
          title: "关西机场 -> 上海浦东",
          description: "吉祥航空 HO1338，飞行约2.5小时",
          type: "transport",
          duration: "2.5h",
          location: { lat: 34.4320, lng: 135.2304, label: "关西国际机场" },
        },
      ],
    },
  ],
  budget: {
    totalBudget: 20000,
    totalSpent: 17860,
    currency: "CNY",
    items: [
      // Transport
      {
        id: "b-001",
        category: "transport",
        name: "上海-东京 往返机票 x2",
        amount: 4200,
        currency: "CNY",
        note: "春秋航空特价",
      },
      {
        id: "b-002",
        category: "transport",
        name: "东京-大阪 新干线 x2",
        amount: 1800,
        currency: "CNY",
        day: 3,
        note: "Nozomi 指定席",
      },
      {
        id: "b-003",
        category: "transport",
        name: "成田特快 N'EX x2",
        amount: 400,
        currency: "CNY",
        day: 1,
      },
      {
        id: "b-004",
        category: "transport",
        name: "南海电铁 Rapi:t x2",
        amount: 250,
        currency: "CNY",
        day: 5,
      },
      {
        id: "b-005",
        category: "transport",
        name: "市内交通 (地铁/公交) 5天",
        amount: 600,
        currency: "CNY",
      },
      // Accommodation
      {
        id: "b-006",
        category: "accommodation",
        name: "新宿华盛顿酒店 2晚",
        amount: 2400,
        currency: "CNY",
        day: 1,
        note: "标准双床房",
      },
      {
        id: "b-007",
        category: "accommodation",
        name: "大阪难波东方酒店 2晚",
        amount: 2000,
        currency: "CNY",
        day: 3,
        note: "高级双床房",
      },
      // Food
      {
        id: "b-008",
        category: "food",
        name: "Day1 餐饮",
        amount: 400,
        currency: "CNY",
        day: 1,
        note: "一蘭拉面 + 便利店",
      },
      {
        id: "b-009",
        category: "food",
        name: "Day2 餐饮",
        amount: 700,
        currency: "CNY",
        day: 2,
        note: "筑地海鲜丼 + 叙叙苑烤肉",
      },
      {
        id: "b-010",
        category: "food",
        name: "Day3 餐饮",
        amount: 600,
        currency: "CNY",
        day: 3,
        note: "道顿堀小吃 + 居酒屋",
      },
      {
        id: "b-011",
        category: "food",
        name: "Day4 餐饮",
        amount: 500,
        currency: "CNY",
        day: 4,
        note: "黑门市场 + 炸串",
      },
      {
        id: "b-012",
        category: "food",
        name: "Day5 餐饮",
        amount: 300,
        currency: "CNY",
        day: 5,
        note: "酒店早餐 + 机场",
      },
      // Tickets
      {
        id: "b-013",
        category: "ticket",
        name: "新宿御苑门票 x2",
        amount: 30,
        currency: "CNY",
        day: 1,
      },
      {
        id: "b-014",
        category: "ticket",
        name: "东京晴空塔门票 x2",
        amount: 240,
        currency: "CNY",
        day: 2,
      },
      {
        id: "b-015",
        category: "ticket",
        name: "大阪城天守阁门票 x2",
        amount: 60,
        currency: "CNY",
        day: 4,
      },
      {
        id: "b-016",
        category: "ticket",
        name: "通天阁门票 x2",
        amount: 60,
        currency: "CNY",
        day: 4,
      },
      {
        id: "b-017",
        category: "ticket",
        name: "天王寺动物园门票 x2",
        amount: 40,
        currency: "CNY",
        day: 4,
      },
      {
        id: "b-018",
        category: "ticket",
        name: "梅田空中庭园门票 x2",
        amount: 80,
        currency: "CNY",
        day: 4,
      },
      // Other
      {
        id: "b-019",
        category: "other",
        name: "旅行保险 x2",
        amount: 200,
        currency: "CNY",
      },
      {
        id: "b-020",
        category: "other",
        name: "随身 WiFi 租赁 5天",
        amount: 100,
        currency: "CNY",
      },
      {
        id: "b-021",
        category: "other",
        name: "伴手礼 & 购物预留",
        amount: 2800,
        currency: "CNY",
      },
    ],
  },
};
