# Export and share API routes
from __future__ import annotations

import hashlib
import json
import logging
from typing import Any, Dict

from fastapi import APIRouter
from fastapi.responses import HTMLResponse, JSONResponse

from agent.db.repositories.itinerary_repo import ItineraryRepository

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api", tags=["export"])

_repo = ItineraryRepository()

# In-memory share link store (keyed by share_id → itinerary_id)
_share_store: Dict[str, str] = {}


@router.post("/itineraries/{itinerary_id}/export")
async def export_itinerary(itinerary_id: str, format: str = "html"):
  """Export an itinerary as printable HTML.

  The client can use window.print() to save as PDF.
  """
  try:
    item = await _repo.get_by_id(itinerary_id)
    if not item:
      return JSONResponse(
        status_code=404,
        content={"error": f"Itinerary '{itinerary_id}' not found"},
      )

    html = _render_itinerary_html(item)
    return HTMLResponse(content=html)
  except Exception as exc:
    logger.exception("Export itinerary error")
    return JSONResponse(status_code=500, content={"error": str(exc)})


@router.post("/itineraries/{itinerary_id}/share")
async def share_itinerary(itinerary_id: str):
  """Generate a share link for an itinerary."""
  try:
    item = await _repo.get_by_id(itinerary_id)
    if not item:
      return JSONResponse(
        status_code=404,
        content={"error": f"Itinerary '{itinerary_id}' not found"},
      )

    share_id = hashlib.md5(itinerary_id.encode()).hexdigest()[:10]
    _share_store[share_id] = itinerary_id

    return {
      "share_id": share_id,
      "share_url": f"/api/shared/{share_id}",
    }
  except Exception as exc:
    logger.exception("Share itinerary error")
    return JSONResponse(status_code=500, content={"error": str(exc)})


@router.get("/shared/{share_id}")
async def get_shared_itinerary(share_id: str):
  """View a shared itinerary (read-only)."""
  try:
    itinerary_id = _share_store.get(share_id)
    if not itinerary_id:
      return JSONResponse(
        status_code=404,
        content={"error": "Share link not found or expired"},
      )

    item = await _repo.get_by_id(itinerary_id)
    if not item:
      return JSONResponse(
        status_code=404,
        content={"error": "Itinerary no longer exists"},
      )

    return item
  except Exception as exc:
    logger.exception("Get shared itinerary error")
    return JSONResponse(status_code=500, content={"error": str(exc)})


def _render_itinerary_html(data: Dict[str, Any]) -> str:
  """Render itinerary data as printable HTML."""
  title = data.get("title", "Travel Itinerary")
  destination = data.get("destination", "")
  start = data.get("start_date", "")
  end = data.get("end_date", "")
  travelers = data.get("travelers", 1)
  budget = data.get("total_budget", 0)
  currency = data.get("currency", "CNY")
  days = data.get("days", [])

  days_html = ""
  for day in days:
    day_num = day.get("day_number", day.get("day", ""))
    day_title = day.get("title", f"Day {day_num}")
    day_date = day.get("date", "")
    items = day.get("items", [])

    items_html = ""
    for item in items:
      time = item.get("time", "")
      item_title = item.get("title", "")
      desc = item.get("description", "")
      items_html += f"""
        <div style="margin-bottom:12px;padding-left:16px;border-left:3px solid #4f46e5;">
          <div style="font-size:12px;color:#666;">{time}</div>
          <div style="font-weight:600;">{item_title}</div>
          <div style="font-size:13px;color:#555;">{desc}</div>
        </div>"""

    days_html += f"""
      <div style="margin-bottom:24px;">
        <h3 style="margin:0 0 8px;color:#4f46e5;">Day {day_num}: {day_title}</h3>
        <div style="font-size:13px;color:#888;margin-bottom:12px;">{day_date}</div>
        {items_html}
      </div>"""

  return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <title>{title}</title>
  <style>
    body {{ font-family: -apple-system, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; color: #333; }}
    @media print {{ body {{ padding: 20px; }} }}
    h1 {{ color: #1a1a1a; margin-bottom: 4px; }}
    .meta {{ color: #666; font-size: 14px; margin-bottom: 32px; }}
  </style>
</head>
<body>
  <h1>{title}</h1>
  <div class="meta">
    {destination} &middot; {start} ~ {end} &middot; {travelers}人 &middot; {currency} {budget}
  </div>
  {days_html}
  <footer style="margin-top:40px;padding-top:16px;border-top:1px solid #eee;font-size:12px;color:#aaa;">
    Generated by TravelMind
  </footer>
</body>
</html>"""
